CREATE TABLE Presets (
	id INTEGER,
	hash TEXT NOT NULL COLLATE NOCASE,
	name TEXT NULL COLLATE NOCASE,
	engineId INTEGER NOT NULL,
	iwadId INTEGER NULL,
	PRIMARY KEY (id),
	UNIQUE (hash),
	UNIQUE (name),
	FOREIGN KEY (engineId) 
		REFERENCES Engines(id),
	FOREIGN KEY (iwadId) 
		REFERENCES IWADs(id)
)
