INSERT INTO EngineTemplateSettings (engineTemplateId, name, value) VALUES
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom'), 'setup.exe.name', 'setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom'), 'server.exe.name', 'sersetup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom'), 'regex.demos', '.+\.lmp'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom'), 'regex.screenshots', 'DOOM[0-9]+\.pcx'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom'), 'regex.saves', 'doomsav[0-9]\.dsg'),

	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom2'), 'setup.exe.name', 'setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom2'), 'server.exe.name', 'sersetup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom2'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom2'), 'regex.demos', '.+\.lmp'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom2'), 'regex.screenshots', 'DOOM[0-9]+\.pcx'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-doom2'), 'regex.saves', 'doomsav[0-9]\.dsg'),

	((SELECT id FROM EngineTemplates WHERE name = 'dos-heretic'), 'setup.exe.name', 'setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-heretic'), 'server.exe.name', 'sersetup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-heretic'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-heretic'), 'regex.demos', '.+\.lmp'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-heretic'), 'regex.screenshots', 'HTIC[0-9]+\.pcx'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-heretic'), 'regex.saves', 'hticsav[0-9]\.hsg'),

	((SELECT id FROM EngineTemplates WHERE name = 'dos-hexen'), 'setup.exe.name', 'setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-hexen'), 'server.exe.name', 'sersetup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-hexen'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-hexen'), 'regex.demos', '.+\.lmp'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-hexen'), 'regex.screenshots', 'HEXEN[0-9]+\.pcx'),

	((SELECT id FROM EngineTemplates WHERE name = 'dos-strife'), 'setup.exe.name', 'setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-strife'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-strife'), 'regex.screenshots', 'STRIFE[0-9]+\.pcx'),
	((SELECT id FROM EngineTemplates WHERE name = 'dos-strife'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'setup.exe.name', 'chocolate-doom-setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'switch.file', '-merge'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'switch.dehlump', '-dehlump'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'regex.screenshots', 'DOOM[0-9]+\.(pcx|png|bmp|gif)'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-doom'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'setup.exe.name', 'chocolate-heretic-setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'switch.file', '-merge'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'switch.dehlump', '-dehlump'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'regex.screenshots', 'HTIC[0-9]+\.(pcx|png|bmp|gif)'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-heretic'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'setup.exe.name', 'chocolate-hexen-setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'switch.file', '-merge'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'switch.dehlump', '-dehlump'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'regex.screenshots', 'HEXEN[0-9]+\.(pcx|png|bmp|gif)'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-hexen'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'setup.exe.name', 'chocolate-strife-setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'switch.file', '-merge'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'switch.dehlump', '-dehlump'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'regex.screenshots', 'STRIFE[0-9]+\.(pcx|png|bmp|gif)'),
	((SELECT id FROM EngineTemplates WHERE name = 'chocolate-strife'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'setup.exe.name', 'crispy-doom-setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'switch.file', '-merge'),
	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'regex.screenshots', 'DOOM[0-9]+\.(pcx|png|bmp|gif)'),
	((SELECT id FROM EngineTemplates WHERE name = 'crispy'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'dsda-doom'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'dsda-doom'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'dsda-doom'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'dsda-doom'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'dsda-doom'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'setup.exe.name', 'woof-setup.exe'),
	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'switch.save.dir', '-save'),
	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'woof'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'doom-retro'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'doom-retro'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'doom-retro'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'doom-retro'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'doom-retro'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'doom-retro'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'nugget'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'nugget'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'nugget'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'nugget'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'nugget'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'nugget'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'zdoom'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'zdoom'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'zdoom'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'zdoom'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'zdoom'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'zdoom'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'gzdoom'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'gzdoom'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'gzdoom'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'gzdoom'), 'switch.save.dir', '-savedir'),
	((SELECT id FROM EngineTemplates WHERE name = 'gzdoom'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'gzdoom'), 'regex.demos', '.+\.lmp'),

	((SELECT id FROM EngineTemplates WHERE name = 'eternity'), 'switch.file', '-file'),
	((SELECT id FROM EngineTemplates WHERE name = 'eternity'), 'switch.dehacked', '-deh'),
	((SELECT id FROM EngineTemplates WHERE name = 'eternity'), 'switch.iwad', '-iwad'),
	((SELECT id FROM EngineTemplates WHERE name = 'eternity'), 'switch.save.dir', '-save'),
	((SELECT id FROM EngineTemplates WHERE name = 'eternity'), 'switch.screenshots.dir', '-shotdir'),
	((SELECT id FROM EngineTemplates WHERE name = 'eternity'), 'regex.demos', '.+\.lmp')
