CREATE TABLE Preset (
	id INTEGER,
	hash TEXT NOT NULL,
	name TEXT NULL COLLATE NOCASE,
	engineId TEXT NOT NULL,
	iwadId TEXT NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (hash),
	UNIQUE (name),
	FOREIGN KEY (engineId) 
		REFERENCES Engines(id),
	FOREIGN KEY (iwadId) 
		REFERENCES IWADs(id)
)
